name = "redact-iq"
compatibility_date = "2023-12-01"

[env.production]
routes = [
  { pattern = "redactiq.com", custom_domain = true },
  { pattern = "www.redactiq.com", custom_domain = true }
]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200